#!/usr/bin/env bash

function usage
{
    echo >&2 "usage: $0 USERNAME"
}

if [ $# -ne 1 ]
then
    usage
    exit 1
fi

USERNAME=$1
PASSWORD=$(head -c32 /dev/urandom | md5sum | awk '// { print $1; }')

ID=$(docker-compose ps -q smtpd)
CRYPTED=$(docker exec $ID smtpctl encrypt $PASSWORD)

# we need extra :::: fields for dovecot here (expects a valid passwd file)
echo -e "${USERNAME}:${CRYPTED}:::::" >> data/users.db

docker-compose restart smtpd
docker-compose restart dovecot

echo "Added user $USERNAME identified by $PASSWORD"
