smtpd:
  build: docker/opensmtpd
  volumes:
  - data/confs/mail.crt:/etc/ssl/mail.crt
  - data/confs/mail.key:/etc/ssl/private/mail.key
  - data/confs/aliases:/etc/aliases
  - data/confs/smtpd.conf:/etc/smtpd.conf
  - data/confs/mailname:/etc/mailname
  - data/maildirs:/home
  - data/users.db:/etc/users.db
  ports:
  - "25:25"
  - "587:587"
  links:
  - dovecot
  - spamd

dovecot:
  build: docker/dovecot
  volumes:
  - data/confs/mail.crt:/etc/pki/tls/certs/mail.crt
  - data/confs/mail.key:/etc/ssl/private/mail.key
  - data/users.db:/etc/users.db
  - data/maildirs:/var/mail
  ports:
  - "993:993"
  - "143:143"
  expose:
  - "993"
  - "143"

spamd:
  build: docker/spamd

roundcube:
  build: docker/roundcube
  environment:
  - VIRTUAL_HOST=rain.sbrk.org
  volumes:
  - data/confs/virtualhost.conf:/etc/apache2/sites-available/roundcube.conf
  expose:
  - "80"
  links:
  - dovecot
